import OpenAI from 'openai';
import { OpenAIResponseHandler } from './OpenAIResponseHandler';
import type { AIAgent } from '../types';
import type { Channel, DefaultGenerics, Event, StreamChat } from 'stream-chat';

export class OpenAIAgent implements AIAgent {
  private openai?: OpenAI;
  private lastInteractionTs = Date.now();

  private handlers: OpenAIResponseHandler[] = [];

  constructor(
    readonly chatClient: StreamChat,
    readonly channel: Channel,
  ) {}

  dispose = async () => {
    this.chatClient.off('message.new', this.handleMessage);
    await this.chatClient.disconnectUser();

    this.handlers.forEach((handler) => handler.dispose());
    this.handlers = [];
  };

  getLastInteraction = (): number => this.lastInteractionTs;

  init = async () => {
    const apiKey = process.env.GITHUBMODELS_API_KEY as string | undefined;
    if (!apiKey) {
      throw new Error('An API key for the LLM is required');
    }

    /**
     * Connection with the assistant
     */
    this.openai = new OpenAI({
      apiKey: process.env.GITHUBMODELS_API_KEY,
      baseURL: 'https://models.github.ai/inference',
    });

    this.chatClient.on('message.new', this.handleMessage);
  };

  private handleMessage = async (e: Event<DefaultGenerics>) => {

    //Verify if the open ai client is connected
    if (!this.openai) {
      console.log('LLM not initialized');
      return;
    }

    // Verify if the message doesnt exist, or if its generated by the ai
    if (!e.message || e.message.ai_generated) {
      console.log('Skip handling ai generated message');
      return;
    }

    /**
     * Extract the message from event
     */
    const message = e.message.text;
    if (!message) return;

    this.lastInteractionTs = Date.now();

    // Send message to open AI api
    // TODO: add messages history
    const response = await this.openai.chat.completions.create({
      model: 'openai/gpt-4.1',
      messages: [
        { role: 'system', content: 'You are a helpful assistant that answers questions.' },
        { role: 'user', content: message }
      ],
    });

    //Send message back to channel
    const assistantText = response.choices?.[0]?.message?.content || '';

    const { message: channelMessage } = await this.channel.sendMessage({
      text: assistantText,
      ai_generated: true,
    });

    //Update channel state, to wait for AI response
    await this.channel.sendEvent({
      type: 'ai_indicator.update',
      ai_state: 'AI_STATE_THINKING',
      cid: channelMessage.cid,
      message_id: channelMessage.id,
    });

    await this.chatClient.partialUpdateMessage(channelMessage.id, {
      set: { assistantText, generating: false },
    });

    await this.channel.sendEvent({
      type: 'ai_indicator.clear',
      cid: channelMessage.cid,
      message_id: channelMessage.id,
    });

  };
}
